In [131]:
import pandas as pd
import glob
import os

In [132]:
os.chdir(r"C:/Users/wafab/http_ids_project")
#load
parquet_files=glob.glob("data/parquet/*.parquet")
print("Found files:", parquet_files)
#concatenate
df_parquet=pd.concat([pd.read_parquet(f) for f in parquet_files],ignore_index=True)
print(f"Total rows : {len(df_parquet)}")
print(df_parquet.columns)

Found files: ['data/parquet\\output_part_0.parquet', 'data/parquet\\output_part_1.parquet', 'data/parquet\\output_part_10.parquet', 'data/parquet\\output_part_11.parquet', 'data/parquet\\output_part_12.parquet', 'data/parquet\\output_part_13.parquet', 'data/parquet\\output_part_14.parquet', 'data/parquet\\output_part_15.parquet', 'data/parquet\\output_part_16.parquet', 'data/parquet\\output_part_17.parquet', 'data/parquet\\output_part_18.parquet', 'data/parquet\\output_part_19.parquet', 'data/parquet\\output_part_2.parquet', 'data/parquet\\output_part_20.parquet', 'data/parquet\\output_part_3.parquet', 'data/parquet\\output_part_4.parquet', 'data/parquet\\output_part_5.parquet', 'data/parquet\\output_part_6.parquet', 'data/parquet\\output_part_7.parquet', 'data/parquet\\output_part_8.parquet', 'data/parquet\\output_part_9.parquet']
Total rows : 2940417
Index(['Entropy_1', 'Entropy_2', 'Entropy_3', 'Entropy_4', 'Entropy_5',
       'Entropy_6', 'Entropy_7', 'Entropy_8', 'Entropy_9', 'Entropy_10',
       ...
       'Header_bit_139', 'Header_bit_140', 'Header_bit_141', 'Header_bit_142',
       'Header_bit_143', 'Header_bit_144', 'PayloadEncoding', 'PayloadStrings',
       'Attack', 'Label'],
      dtype='object', length=158)

In [133]:
#columns useful for NLP : 
nlp_cols= ['PayloadEncoding', 'PayloadStrings','Attack', 'Label']
pd.set_option('display.max_colwidth', None)
df_parquet=df_parquet[nlp_cols]
df_parquet.head(10)

,PayloadEncoding,PayloadStrings,Attack,Label
0,None,None,Benign,Benign
1,MacCyrillic,z=7Ж6VXVHтƒж “aВ:`аs∞ѕ/Эn„:«ЗЌ8—џjТєёи≤p#Ї“еH№нн0µ∆,Benign,Benign
2,None,None,Benign,Benign
3,None,None,Benign,Benign
4,None,None,Benign,Benign
5,None,None,Benign,Benign
6,None,None,Benign,Benign
7,None,None,Benign,Benign
8,MacCyrillic,ЬR†уRH'¶l ©HЭ÷W!F у=#'t‘…jюч@SЙЭ‘3o$ющЖЄи[ЩTЪZ—Т\tЦq.Иа>лывa,Benign,Benign
9,None,None,Benign,Benign

In [134]:
#FILTER ONLY HTTP-LIKE PAYLOADS:
def is_http(payload):
    if not isinstance(payload, str): return False
    return payload.lower().startswith(("get ", "post ", "head ")) and "http/1.1" in payload.lower()

df = df_parquet[df_parquet["PayloadStrings"].apply(is_http)].copy()
df.head(10)

,PayloadEncoding,PayloadStrings,Attack,Label
8166,ascii,"GET /ubuntu/dists/xenial/InRelease HTTP/1.1\r Host: us-east-2.ec2.archive.ubuntu.com\r Cache-Control: max-age=0\r Accept: text/*\r If-Modified-Since: Thu, 21 Apr 2016 23:24:48 GMT\r User-Agent: Debian APT-HTTP/1.3 (1.2.24)\r \r",Benign,Benign
8169,ascii,"GET /ubuntu/dists/xenial-updates/InRelease HTTP/1.1\r Host: us-east-2.ec2.archive.ubuntu.com\r Cache-Control: max-age=0\r Accept: text/*\r If-Modified-Since: Wed, 14 Feb 2018 18:04:00 GMT\r User-Agent: Debian APT-HTTP/1.3 (1.2.24)\r \r",Benign,Benign
8181,ascii,"GET /ubuntu/dists/xenial-backports/InRelease HTTP/1.1\r Host: us-east-2.ec2.archive.ubuntu.com\r Cache-Control: max-age=0\r Accept: text/*\r If-Modified-Since: Wed, 14 Feb 2018 18:04:00 GMT\r User-Agent: Debian APT-HTTP/1.3 (1.2.24)\r \r",Benign,Benign
8189,ascii,"GET /ubuntu/dists/xenial-security/InRelease HTTP/1.1\r Host: security.ubuntu.com\r Cache-Control: max-age=0\r Accept: text/*\r If-Modified-Since: Wed, 14 Feb 2018 19:08:00 GMT\r User-Agent: Debian APT-HTTP/1.3 (1.2.24)\r \r",Benign,Benign
8190,ascii,GET /ubuntu/dists/xenial-updates/main/source/by-hash/SHA256/2dda3f2b8de307516800ca2121ee87893c84e2ea2e942df8ee261749130c2292 HTTP/1.1\r Host: us-east-2.ec2.archive.ubuntu.com\r Cache-Control: max-age=0\r Accept: text/*\r User-Agent: Debian APT-HTTP/1.3 (1.2.24)\r \r,Benign,Benign
8209,ascii,GET /ubuntu/dists/xenial-updates/universe/source/by-hash/SHA256/f8470b75eebcdc103fe97713447404d70c6e489f4af47a37216d76e7bd95668a HTTP/1.1\r Host: us-east-2.ec2.archive.ubuntu.com\r Cache-Control: max-age=0\r Accept: text/*\r User-Agent: Debian APT-HTTP/1.3 (1.2.24)\r \r,Benign,Benign
8218,ascii,GET /ubuntu/dists/xenial-updates/main/binary-amd64/by-hash/SHA256/64de74595313814f778183f24f18a8a416d31004444fed5b515fbf5681e38f01 HTTP/1.1\r Host: us-east-2.ec2.archive.ubuntu.com\r Cache-Control: max-age=0\r Accept: text/*\r User-Agent: Debian APT-HTTP/1.3 (1.2.24)\r \r,Benign,Benign
8253,ascii,GET /ubuntu/dists/xenial-updates/main/i18n/by-hash/SHA256/6f25a9972e5d30d85ca1504f64590b330b451b28c6694ff7599781a389afb7c2 HTTP/1.1\r Host: us-east-2.ec2.archive.ubuntu.com\r Cache-Control: max-age=0\r Accept: text/*\r User-Agent: Debian APT-HTTP/1.3 (1.2.24)\r \r,Benign,Benign
8271,ascii,GET /ubuntu/dists/xenial-updates/universe/binary-amd64/by-hash/SHA256/b353975a5d4f1a7272a5c785b9132f7b89f89d7d52c54df4d41ab8558d950319 HTTP/1.1\r Host: us-east-2.ec2.archive.ubuntu.com\r Cache-Control: max-age=0\r Accept: text/*\r User-Agent: Debian APT-HTTP/1.3 (1.2.24)\r \r,Benign,Benign
8296,ascii,GET /ubuntu/dists/xenial-updates/universe/i18n/by-hash/SHA256/f401f39ea2728a4033d2de5f6b60b4953cc76dc51a6190ea3eca77993c08e934 HTTP/1.1\r Host: us-east-2.ec2.archive.ubuntu.com\r Cache-Control: max-age=0\r Accept: text/*\r User-Agent: Debian APT-HTTP/1.3 (1.2.24)\r \r,Benign,Benign

In [152]:
df['PayloadStrings'].count()

np.int64(117806)

In [136]:
label_count=df['Label'].value_counts()
print(label_count)
attack_count=df['Attack'].value_counts()
print(f"\n{attack_count}")

Label
Malicious    108239
Benign         9567
Name: count, dtype: int64

Attack
DoS-Slowloris     49405
DoS-GoldenEye     34776
BruteForce-Web    13118
BruteForce-XSS    10889
Benign             9567
SQL Injection        51
Name: count, dtype: int64

In [153]:
import string

In [154]:
encoding_types=df_parquet['PayloadEncoding'].unique().tolist()
print(encoding_types)

[None, 'MacCyrillic', 'KOI8-R', 'Windows-1252', 'IBM866', 'Windows-1251', 'windows-1251', 'MacRoman', 'ascii', 'ISO-8859-1', 'TIS-620', 'IBM855', 'windows-1253', 'Windows-1254', 'ISO-8859-5', 'ISO-8859-7', 'Windows-1253', 'windows-1255', 'ISO-8859-8', 'ISO-8859-9', 'Windows-1255', 'utf-8', 'UTF-16']

In [156]:
def decode_payload(payload):
    if not isinstance(payload,str):
        return ""
    byte_payload= payload.encode('latin-1', errors='ignore')
    for enc in encoding_types:
        try:
            decoded= byte_payload.decode(enc)
        #check if the decoded strings has enough readable and real-like characters to consider it valid, if not => remove them:
        #they are not meaningful for nlp and can trick the model , as it can contain corrupted data in a benign labelling.
            ascii_letters = string.ascii_letters + string.digits + " "
            num_clean = sum(1 for c in decoded if c in ascii_letters)
            if num_clean / max(len(decoded), 1) > 0.6:
                return decoded
        except :
            continue
    return ""

#check whether it's a payoload or a log per attack :
attack_types=df['Attack'].dropna().unique()
pd.set_option("display.max_colwidth", None)  
pd.set_option("display.max_rows", 1000)

for attack in attack_types:
    print(f"\n Attack type: {attack}")
    samples=(df[df['Attack']==attack].copy()
             .dropna(subset=["PayloadStrings"]).head(10))
    for i, raw in enumerate(samples["PayloadStrings"]):
        decoded_payload=decode_payload(raw)
        if decoded_payload:
            print(f"\n --Payload {i+1} --\n{decoded_payload.strip()[:1000]}")

 Attack type: Benign

 --Payload 1 --
GET /ubuntu/dists/xenial/InRelease HTTP/1.1

Host: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* If-Modified-Since: Thu, 21 Apr 2016 23:24:48 GMT
User-Agent: Debian APT-HTTP/1.3 (1.2.24)

 --Payload 2 --
GET /ubuntu/dists/xenial-updates/InRelease HTTP/1.1

Host: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* If-Modified-Since: Wed, 14 Feb 2018 18:04:00 GMT
User-Agent: Debian APT-HTTP/1.3 (1.2.24)

 --Payload 3 --
GET /ubuntu/dists/xenial-backports/InRelease HTTP/1.1

Host: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* If-Modified-Since: Wed, 14 Feb 2018 18:04:00 GMT
User-Agent: Debian APT-HTTP/1.3 (1.2.24)

 --Payload 4 --
GET /ubuntu/dists/xenial-security/InRelease HTTP/1.1

Host: security.ubuntu.com Cache-Control: max-age=0 Accept: text/* If-Modified-Since: Wed, 14 Feb 2018 19:08:00 GMT
User-Agent: Debian APT-HTTP/1.3 (1.2.24)

 --Payload 5 --
GET /ubuntu/dists/xenial-updates/main/source/by-hash/SHA256/2dda3f2b8de307516800ca2121ee87893c84e2ea2e942df8ee261749130c2292 HTTP/1.1

Host: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/*
User-Agent: Debian APT-HTTP/1.3 (1.2.24)

 --Payload 6 --
GET /ubuntu/dists/xenial-updates/universe/source/by-hash/SHA256/f8470b75eebcdc103fe97713447404d70c6e489f4af47a37216d76e7bd95668a HTTP/1.1

Host: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/*
User-Agent: Debian APT-HTTP/1.3 (1.2.24)

 --Payload 7 --
GET /ubuntu/dists/xenial-updates/main/binary-amd64/by-hash/SHA256/64de74595313814f778183f24f18a8a416d31004444fed5b515fbf5681e38f01 HTTP/1.1

Host: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/*
User-Agent: Debian APT-HTTP/1.3 (1.2.24)

 --Payload 8 --
GET /ubuntu/dists/xenial-updates/main/i18n/by-hash/SHA256/6f25a9972e5d30d85ca1504f64590b330b451b28c6694ff7599781a389afb7c2 HTTP/1.1

Host: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/*
User-Agent: Debian APT-HTTP/1.3 (1.2.24)

 --Payload 9 --
GET /ubuntu/dists/xenial-updates/universe/binary-amd64/by-hash/SHA256/b353975a5d4f1a7272a5c785b9132f7b89f89d7d52c54df4d41ab8558d950319 HTTP/1.1

Host: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/*
User-Agent: Debian APT-HTTP/1.3 (1.2.24)

 --Payload 10 --
GET /ubuntu/dists/xenial-updates/universe/i18n/by-hash/SHA256/f401f39ea2728a4033d2de5f6b60b4953cc76dc51a6190ea3eca77993c08e934 HTTP/1.1

Host: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/*
User-Agent: Debian APT-HTTP/1.3 (1.2.24)

 Attack type: DoS-GoldenEye

 --Payload 1 --
GET /?yeFaFPSPb=C7QyhPv&UgNKvIPsv=7vDJjMKyc&Q5KQiWMnne=4TT6pw03jcLuu8W HTTP/1.1
Accept-Encoding: '', gzip
Host: 18.217.21.148 Keep-Alive: 517 Connection: keep-alive
Referer: http://18.217.21.148/YIR0C8x Cache-Control: max-age=0
Cookie: jJnyonYef=voS7nKir268erKjAu&KBTnQFuQWA=ETAvm&mj3f1pt=l8Aq8Gh7vIjmu
User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) Gecko/20092106 Firefox/12.0

 --Payload 2 --
GET /?cMgN=Iwh0UIGqayR&1t7gnC1=v2T1nWYAOWpd0ECMTS1r HTTP/1.1
Accept-Encoding: identity Keep-Alive: 934
Host: 18.217.21.148
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0) Gecko/20082209 Firefox/10.0 Connection: keep-alive Cache-Control: no-cache
Content-Type: multipart/form-data

 --Payload 3 --
GET /?5r2ffD1=pnaBtx3GjwMBFjNoePh&xgBDaYC2=Mw5ybqlnExlb7u0CasuK&xlfGGvhJu=2nvBaDW7tWt&aopieOt=WSjHgE5fUNM&ULccVX=KkBpebM1 HTTP/1.1

Host: 18.217.21.148 Accept-Encoding: deflate Keep-Alive: 937
User-Agent: Mozilla/5.0 (Windows; U; MSIE 10.0; Windows NT 6.1; Trident/4.0; Win64; x64) Connection: keep-alive Cache-Control: no-cache
Content-Type: application/x-url-encoded

 --Payload 4 --
GET /?dsytCyvo=BprUMPc66D70xCs HTTP/1.1
Accept-Encoding: gzip, '' Connection: keep-alive Keep-Alive: 690
User-Agent: Mozilla/5.0 (Linux i386; X11) Gecko/20101803 Firefox/11.0
Host: 18.217.21.148
Cookie: dRL=iaGPkCLo6KKNUMCbgrf Cache-Control: max-age=0
Referer: http://18.217.21.148/7tWmmR7YnX?yJuTyG=LiMNIp68m1D

 --Payload 5 --
GET /?HlbobF=O2lTi7iqK HTTP/1.1
Accept-Encoding: '', identity Connection: keep-alive Keep-Alive: 723
User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.1; .NET CLR 2.5.4620; Win64; x64)
Host: 18.217.21.148
Referer: http://www.baidu.com/XHOtd Cache-Control: max-age=0
Cookie: 1bvxyP=MfGkMyi8X0gC&T14KAsos=KNLYiXms3hdr6ODMTX&1kCf=JGA4XrluHYlE4TsmK
Content-Type: multipart/form-data

 --Payload 6 --
GET /?Ymi5PsAn=yEtDvx56je0cx HTTP/1.1
Accept-Encoding: '' Keep-Alive: 5
Host: 18.217.21.148
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_1) AppleWebKit/537.8 (KHTML, like Gecko) Chrome/18.0.847.90 Safari/537.10 Accept-Charset: utf-8,ISO-8859-2;q=0.9,*;q=0.6 Connection: keep-alive
Cookie: UojYX0=FTtQ&wlobX=7GuEcwq&QpwT5l=pcjk Cache-Control: no-cache
Content-Type: application/x-url-encoded

 --Payload 7 --
GET /?634m=AN8I5twujO8Aw1TYAiv&FF0=CljAq6CMSYx6cUajNDY&IRHNfeMU=g2KmJKWbrTikFJs5 HTTP/1.1
Accept-Encoding: gzip, '' Keep-Alive: 908
Host: 18.217.21.148
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_9_4) Gecko/20020806 Firefox/19.0 Accept-Charset: utf-8,Windows-1251;q=0.9,*;q=0.0 Connection: keep-alive Cache-Control: max-age=0

 --Payload 8 --
GET /?qq1hqOmm=GUntnLX&HB5=4hdF5Yf2Dx&I8NO=5CanyhF HTTP/1.1
Accept-Encoding: identity, deflate Connection: keep-alive Keep-Alive: 781
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_8_3) Gecko/20102409 Firefox/17.0 Accept-Charset: ISO-8859-2,Windows-1251;q=1.0,*;q=1.0
Host: 18.217.21.148
Cookie: R6t=VPRyUTW&igOHQ=klb5nfnIl3vLs8DeeUOE&akTr=tcWsR0NdxF Cache-Control: max-age=0

 --Payload 9 --
GET /?oKtlKK=Ww80vxt&yReef=2QTGol2k&xpWYhR=MDhRkhjmRWy&JeFo6ayeTp=GQkgA1k HTTP/1.1
Accept-Encoding: identity, '' Keep-Alive: 844
Host: 18.217.21.148
User-Agent: Mozilla/5.0 (compatible; MSIE 10.0; Linux x86_64; .NET CLR 1.2.7340; X11) Connection: keep-alive
Cookie: V74hgcr05=CUTK Cache-Control: max-age=0
Referer: http://www.google.com/yvmFXKF1?nnH=T6h
Content-Type: multipart/form-data

 --Payload 10 --
GET /?YnpH7om2i=Bx6gsO1mkKFOfMmg2h&tm30QHv=mIoB3Xe5bCPEnlE HTTP/1.1
Accept-Encoding: identity Connection: keep-alive Keep-Alive: 948
User-Agent: Mozilla/5.0 (Linux i386; X11) AppleWebKit/536.17 (KHTML, like Gecko) Chrome/32.0.1566.28 Safari/535.6 Accept-Charset: utf-8,Windows-1251;q=0.8,*;q=0.4
Host: 18.217.21.148
Cookie: AAD=gJfD6St Cache-Control: no-cache

 Attack type: DoS-Slowloris

 --Payload 1 --
GET / HTTP/1.1

Host: 18.217.21.148
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 1.1.4322; .NET CLR 2.0.503l3; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; MSOffice 12) Content-Length: 42

 --Payload 2 --
GET / HTTP/1.1

Host: 18.217.21.148
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 1.1.4322; .NET CLR 2.0.503l3; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; MSOffice 12) Content-Length: 42

 --Payload 3 --
GET / HTTP/1.1

Host: 18.217.21.148
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 1.1.4322; .NET CLR 2.0.503l3; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; MSOffice 12) Content-Length: 42

 --Payload 4 --
GET / HTTP/1.1

Host: 18.217.21.148
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 1.1.4322; .NET CLR 2.0.503l3; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; MSOffice 12) Content-Length: 42

 --Payload 5 --
GET / HTTP/1.1

Host: 18.217.21.148
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 1.1.4322; .NET CLR 2.0.503l3; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; MSOffice 12) Content-Length: 42

 --Payload 6 --
GET / HTTP/1.1

Host: 18.217.21.148
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 1.1.4322; .NET CLR 2.0.503l3; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; MSOffice 12) Content-Length: 42

 --Payload 7 --
GET / HTTP/1.1

Host: 18.217.21.148
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 1.1.4322; .NET CLR 2.0.503l3; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; MSOffice 12) Content-Length: 42

 --Payload 8 --
GET / HTTP/1.1

Host: 18.217.21.148
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 1.1.4322; .NET CLR 2.0.503l3; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; MSOffice 12) Content-Length: 42

 --Payload 9 --
GET / HTTP/1.1

Host: 18.217.21.148
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 1.1.4322; .NET CLR 2.0.503l3; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; MSOffice 12) Content-Length: 42

 --Payload 10 --
GET / HTTP/1.1

Host: 18.217.21.148
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 1.1.4322; .NET CLR 2.0.503l3; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; MSOffice 12) Content-Length: 42

 Attack type: BruteForce-Web

 --Payload 1 --
GET /DVWA/login.php HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate Connection: keep-alive Upgrade-Insecure-Requests: 1

 --Payload 2 --
GET /DVWA/dvwa/css/login.css HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: text/css,*/*;q=0.1 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Referer: http://18.218.83.150/DVWA/login.php
Cookie: security=impossible; PHPSESSID=qq3tfhbcgq1ekqqaaqsr9cit75 Connection: keep-alive

 --Payload 3 --
GET /DVWA/dvwa/images/login_logo.png HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: */* Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Referer: http://18.218.83.150/DVWA/login.php
Cookie: security=impossible; PHPSESSID=qq3tfhbcgq1ekqqaaqsr9cit75 Connection: keep-alive

 --Payload 4 --
GET /favicon.ico HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Cookie: PHPSESSID=qq3tfhbcgq1ekqqaaqsr9cit75 Connection: keep-alive

 --Payload 5 --
POST /DVWA/login.php HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Referer: http://18.218.83.150/DVWA/login.php
Content-Type: application/x-www-form-urlencoded Content-Length: 130
Cookie: security=impossible; PHPSESSID=qq3tfhbcgq1ekqqaaqsr9cit75 Connection: keep-alive Upgrade-Insecure-Requests: 1 username=admin&password=OLHKS72F6MZM6MEC7TXZEN5ZXCLLJXBRQXT8MZKOQFLYW3FXFU&Login=Login&user_token=db315f62e15c8b63974b7c7a45ca6e16

 --Payload 6 --
GET /DVWA/login.php HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Referer: http://18.218.83.150/DVWA/login.php
Cookie: security=impossible; PHPSESSID=qq3tfhbcgq1ekqqaaqsr9cit75 Connection: keep-alive Upgrade-Insecure-Requests: 1

 --Payload 7 --
POST /DVWA/login.php HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Referer: http://18.218.83.150/DVWA/login.php
Content-Type: application/x-www-form-urlencoded Content-Length: 130
Cookie: security=impossible; PHPSESSID=qq3tfhbcgq1ekqqaaqsr9cit75 Connection: keep-alive Upgrade-Insecure-Requests: 1 username=admin&password=CF47PP2Y3X4Z3L5VVNISVXVWVE7T0IP7UEXWSHPNPO9KWM0QAA&Login=Login&user_token=ab780f85c9618e6d8460db0a5989b1f1

 --Payload 8 --
GET /DVWA/login.php HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Referer: http://18.218.83.150/DVWA/login.php
Cookie: security=impossible; PHPSESSID=qq3tfhbcgq1ekqqaaqsr9cit75 Connection: keep-alive Upgrade-Insecure-Requests: 1

 --Payload 9 --
POST /DVWA/login.php HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Referer: http://18.218.83.150/DVWA/login.php
Content-Type: application/x-www-form-urlencoded Content-Length: 130
Cookie: security=impossible; PHPSESSID=qq3tfhbcgq1ekqqaaqsr9cit75 Connection: keep-alive Upgrade-Insecure-Requests: 1 username=admin&password=3XGAFXTS9LYRUTD5X7QQWU7XYXY5LUX726LEYX21HJUU1VDGAF&Login=Login&user_token=5c3217ef157aff9d285a894397fd0e59

 --Payload 10 --
GET /DVWA/login.php HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Referer: http://18.218.83.150/DVWA/login.php
Cookie: security=impossible; PHPSESSID=qq3tfhbcgq1ekqqaaqsr9cit75 Connection: keep-alive Upgrade-Insecure-Requests: 1

 Attack type: BruteForce-XSS

 --Payload 1 --
GET /DVWA/vulnerabilities/xss_r/ HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate Connection: keep-alive Upgrade-Insecure-Requests: 1

 --Payload 2 --
GET /DVWA/login.php HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Cookie: PHPSESSID=s7e2ta4n14qogn3kdvnm9rg907 Connection: keep-alive Upgrade-Insecure-Requests: 1

 --Payload 3 --
GET /DVWA/dvwa/css/login.css HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: text/css,*/*;q=0.1 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Referer: http://18.218.83.150/DVWA/login.php
Cookie: security=impossible; PHPSESSID=s7e2ta4n14qogn3kdvnm9rg907 Connection: keep-alive

 --Payload 4 --
GET /DVWA/dvwa/images/login_logo.png HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: */* Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Referer: http://18.218.83.150/DVWA/login.php
Cookie: security=impossible; PHPSESSID=s7e2ta4n14qogn3kdvnm9rg907 Connection: keep-alive

 --Payload 5 --
GET /favicon.ico HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Cookie: PHPSESSID=s7e2ta4n14qogn3kdvnm9rg907 Connection: keep-alive

 --Payload 6 --
POST /DVWA/login.php HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Referer: http://18.218.83.150/DVWA/login.php
Content-Type: application/x-www-form-urlencoded Content-Length: 88
Cookie: security=impossible; PHPSESSID=s7e2ta4n14qogn3kdvnm9rg907 Connection: keep-alive Upgrade-Insecure-Requests: 1 username=admin&password=password&Login=Login&user_token=8b9f4581ed6e655f762926732a570b58

 --Payload 7 --
GET /DVWA/index.php HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Referer: http://18.218.83.150/DVWA/login.php
Cookie: security=impossible; PHPSESSID=s7e2ta4n14qogn3kdvnm9rg907 Connection: keep-alive Upgrade-Insecure-Requests: 1

 --Payload 8 --
GET /DVWA/dvwa/css/main.css HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: text/css,*/*;q=0.1 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Referer: http://18.218.83.150/DVWA/index.php
Cookie: security=impossible; PHPSESSID=s7e2ta4n14qogn3kdvnm9rg907 Connection: keep-alive

 --Payload 9 --
GET /DVWA/dvwa/js/dvwaPage.js HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: */* Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Referer: http://18.218.83.150/DVWA/index.php
Cookie: security=impossible; PHPSESSID=s7e2ta4n14qogn3kdvnm9rg907 Connection: keep-alive

 --Payload 10 --
GET /DVWA/dvwa/images/logo.png HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: */* Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Referer: http://18.218.83.150/DVWA/index.php
Cookie: security=impossible; PHPSESSID=s7e2ta4n14qogn3kdvnm9rg907 Connection: keep-alive

 Attack type: SQL Injection

 --Payload 1 --
GET /DVWA/ HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Cookie: security=impossible; PHPSESSID=s7e2ta4n14qogn3kdvnm9rg907 Connection: keep-alive Upgrade-Insecure-Requests: 1

 --Payload 2 --
GET /DVWA/login.php HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Cookie: security=impossible; PHPSESSID=s7e2ta4n14qogn3kdvnm9rg907 Connection: keep-alive Upgrade-Insecure-Requests: 1

 --Payload 3 --
POST /DVWA/login.php HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Referer: http://18.218.83.150/DVWA/login.php
Content-Type: application/x-www-form-urlencoded Content-Length: 88
Cookie: security=impossible; PHPSESSID=s7e2ta4n14qogn3kdvnm9rg907 Connection: keep-alive Upgrade-Insecure-Requests: 1 username=admin&password=password&Login=Login&user_token=eb6878ce3376a7d7f5005505cbfb546a

 --Payload 4 --
GET /DVWA/index.php HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Referer: http://18.218.83.150/DVWA/login.php
Cookie: security=impossible; PHPSESSID=s7e2ta4n14qogn3kdvnm9rg907 Connection: keep-alive Upgrade-Insecure-Requests: 1

 --Payload 5 --
GET /DVWA/security.php HTTP/1.1

Host: 18.218.83.150
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate
Referer: http://18.218.83.150/DVWA/index.php

In [157]:
df['PayloadStrings'] = df['PayloadStrings'].apply(decode_payload)
df= df[df['PayloadStrings'].str.strip() != ""]

In [158]:
df.head(10)

,PayloadEncoding,PayloadStrings,Attack,Label,Parsed
8166,ascii,"GET /ubuntu/dists/xenial/InRelease HTTP/1.1\n\nHost: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* If-Modified-Since: Thu, 21 Apr 2016 23:24:48 GMT \nUser-Agent: Debian APT-HTTP/1.3 (1.2.24)",Benign,Benign,None
8169,ascii,"GET /ubuntu/dists/xenial-updates/InRelease HTTP/1.1\n\nHost: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* If-Modified-Since: Wed, 14 Feb 2018 18:04:00 GMT \nUser-Agent: Debian APT-HTTP/1.3 (1.2.24)",Benign,Benign,None
8181,ascii,"GET /ubuntu/dists/xenial-backports/InRelease HTTP/1.1\n\nHost: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* If-Modified-Since: Wed, 14 Feb 2018 18:04:00 GMT \nUser-Agent: Debian APT-HTTP/1.3 (1.2.24)",Benign,Benign,None
8189,ascii,"GET /ubuntu/dists/xenial-security/InRelease HTTP/1.1\n\nHost: security.ubuntu.com Cache-Control: max-age=0 Accept: text/* If-Modified-Since: Wed, 14 Feb 2018 19:08:00 GMT \nUser-Agent: Debian APT-HTTP/1.3 (1.2.24)",Benign,Benign,None
8190,ascii,GET /ubuntu/dists/xenial-updates/main/source/by-hash/SHA256/2dda3f2b8de307516800ca2121ee87893c84e2ea2e942df8ee261749130c2292 HTTP/1.1\n\nHost: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* \nUser-Agent: Debian APT-HTTP/1.3 (1.2.24),Benign,Benign,None
8209,ascii,GET /ubuntu/dists/xenial-updates/universe/source/by-hash/SHA256/f8470b75eebcdc103fe97713447404d70c6e489f4af47a37216d76e7bd95668a HTTP/1.1\n\nHost: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* \nUser-Agent: Debian APT-HTTP/1.3 (1.2.24),Benign,Benign,None
8218,ascii,GET /ubuntu/dists/xenial-updates/main/binary-amd64/by-hash/SHA256/64de74595313814f778183f24f18a8a416d31004444fed5b515fbf5681e38f01 HTTP/1.1\n\nHost: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* \nUser-Agent: Debian APT-HTTP/1.3 (1.2.24),Benign,Benign,None
8253,ascii,GET /ubuntu/dists/xenial-updates/main/i18n/by-hash/SHA256/6f25a9972e5d30d85ca1504f64590b330b451b28c6694ff7599781a389afb7c2 HTTP/1.1\n\nHost: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* \nUser-Agent: Debian APT-HTTP/1.3 (1.2.24),Benign,Benign,None
8271,ascii,GET /ubuntu/dists/xenial-updates/universe/binary-amd64/by-hash/SHA256/b353975a5d4f1a7272a5c785b9132f7b89f89d7d52c54df4d41ab8558d950319 HTTP/1.1\n\nHost: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* \nUser-Agent: Debian APT-HTTP/1.3 (1.2.24),Benign,Benign,None
8296,ascii,GET /ubuntu/dists/xenial-updates/universe/i18n/by-hash/SHA256/f401f39ea2728a4033d2de5f6b60b4953cc76dc51a6190ea3eca77993c08e934 HTTP/1.1\n\nHost: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* \nUser-Agent: Debian APT-HTTP/1.3 (1.2.24),Benign,Benign,None

 ***Not all the rows in PayloadStrings are real payloads , some of them are tools outpout such as NMAP/ scanner or banners (SSH, SMTP, FTP) , therefore i will drop them, only to focus on payload-based attacks , especially that the number of infiltration attacks is very small in cic ids 2018 data.***

In [159]:
from nlp_preprocessing.text_cleaner import clean_text,clean_cookies
import re

In [160]:
def clean_payload_basic(payload):
    if not isinstance(payload, str):
        return ""
    payload = re.sub(r"[\x00-\x1f\x7f]", " ", payload)          
    payload = re.sub(r"[\[\]{}<>]", " ", payload)               
    payload = re.sub(r"\s+", " ", payload)                      
    return payload.strip()

df['PayloadStrings'] = df['PayloadStrings'].apply(clean_payload_basic)
#df['nlp_text'] = df['PayloadStrings'].apply(clean_text)

In [162]:
df.head(10)

,PayloadEncoding,PayloadStrings,Attack,Label,Parsed
8166,ascii,"GET /ubuntu/dists/xenial/InRelease HTTP/1.1 Host: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* If-Modified-Since: Thu, 21 Apr 2016 23:24:48 GMT User-Agent: Debian APT-HTTP/1.3 (1.2.24)",Benign,Benign,None
8169,ascii,"GET /ubuntu/dists/xenial-updates/InRelease HTTP/1.1 Host: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* If-Modified-Since: Wed, 14 Feb 2018 18:04:00 GMT User-Agent: Debian APT-HTTP/1.3 (1.2.24)",Benign,Benign,None
8181,ascii,"GET /ubuntu/dists/xenial-backports/InRelease HTTP/1.1 Host: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* If-Modified-Since: Wed, 14 Feb 2018 18:04:00 GMT User-Agent: Debian APT-HTTP/1.3 (1.2.24)",Benign,Benign,None
8189,ascii,"GET /ubuntu/dists/xenial-security/InRelease HTTP/1.1 Host: security.ubuntu.com Cache-Control: max-age=0 Accept: text/* If-Modified-Since: Wed, 14 Feb 2018 19:08:00 GMT User-Agent: Debian APT-HTTP/1.3 (1.2.24)",Benign,Benign,None
8190,ascii,GET /ubuntu/dists/xenial-updates/main/source/by-hash/SHA256/2dda3f2b8de307516800ca2121ee87893c84e2ea2e942df8ee261749130c2292 HTTP/1.1 Host: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* User-Agent: Debian APT-HTTP/1.3 (1.2.24),Benign,Benign,None
8209,ascii,GET /ubuntu/dists/xenial-updates/universe/source/by-hash/SHA256/f8470b75eebcdc103fe97713447404d70c6e489f4af47a37216d76e7bd95668a HTTP/1.1 Host: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* User-Agent: Debian APT-HTTP/1.3 (1.2.24),Benign,Benign,None
8218,ascii,GET /ubuntu/dists/xenial-updates/main/binary-amd64/by-hash/SHA256/64de74595313814f778183f24f18a8a416d31004444fed5b515fbf5681e38f01 HTTP/1.1 Host: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* User-Agent: Debian APT-HTTP/1.3 (1.2.24),Benign,Benign,None
8253,ascii,GET /ubuntu/dists/xenial-updates/main/i18n/by-hash/SHA256/6f25a9972e5d30d85ca1504f64590b330b451b28c6694ff7599781a389afb7c2 HTTP/1.1 Host: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* User-Agent: Debian APT-HTTP/1.3 (1.2.24),Benign,Benign,None
8271,ascii,GET /ubuntu/dists/xenial-updates/universe/binary-amd64/by-hash/SHA256/b353975a5d4f1a7272a5c785b9132f7b89f89d7d52c54df4d41ab8558d950319 HTTP/1.1 Host: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* User-Agent: Debian APT-HTTP/1.3 (1.2.24),Benign,Benign,None
8296,ascii,GET /ubuntu/dists/xenial-updates/universe/i18n/by-hash/SHA256/f401f39ea2728a4033d2de5f6b60b4953cc76dc51a6190ea3eca77993c08e934 HTTP/1.1 Host: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* User-Agent: Debian APT-HTTP/1.3 (1.2.24),Benign,Benign,None

In [163]:
def smart_split(payload):
    if not isinstance(payload, str):
        return payload
    if "\n" not in payload:
        payload = payload.replace(" HTTP/1.1 ", " HTTP/1.1\n")
        payload = re.sub(r"(Host:|User-Agent:|Referer:|Content-Type:|Cookie:)", r"\n\1", payload)
    return payload
df["PayloadStrings"] = df["PayloadStrings"].apply(smart_split)

In [164]:
df.head(20)

,PayloadEncoding,PayloadStrings,Attack,Label,Parsed
8166,ascii,"GET /ubuntu/dists/xenial/InRelease HTTP/1.1\n\nHost: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* If-Modified-Since: Thu, 21 Apr 2016 23:24:48 GMT \nUser-Agent: Debian APT-HTTP/1.3 (1.2.24)",Benign,Benign,None
8169,ascii,"GET /ubuntu/dists/xenial-updates/InRelease HTTP/1.1\n\nHost: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* If-Modified-Since: Wed, 14 Feb 2018 18:04:00 GMT \nUser-Agent: Debian APT-HTTP/1.3 (1.2.24)",Benign,Benign,None
8181,ascii,"GET /ubuntu/dists/xenial-backports/InRelease HTTP/1.1\n\nHost: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* If-Modified-Since: Wed, 14 Feb 2018 18:04:00 GMT \nUser-Agent: Debian APT-HTTP/1.3 (1.2.24)",Benign,Benign,None
8189,ascii,"GET /ubuntu/dists/xenial-security/InRelease HTTP/1.1\n\nHost: security.ubuntu.com Cache-Control: max-age=0 Accept: text/* If-Modified-Since: Wed, 14 Feb 2018 19:08:00 GMT \nUser-Agent: Debian APT-HTTP/1.3 (1.2.24)",Benign,Benign,None
8190,ascii,GET /ubuntu/dists/xenial-updates/main/source/by-hash/SHA256/2dda3f2b8de307516800ca2121ee87893c84e2ea2e942df8ee261749130c2292 HTTP/1.1\n\nHost: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* \nUser-Agent: Debian APT-HTTP/1.3 (1.2.24),Benign,Benign,None
8209,ascii,GET /ubuntu/dists/xenial-updates/universe/source/by-hash/SHA256/f8470b75eebcdc103fe97713447404d70c6e489f4af47a37216d76e7bd95668a HTTP/1.1\n\nHost: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* \nUser-Agent: Debian APT-HTTP/1.3 (1.2.24),Benign,Benign,None
8218,ascii,GET /ubuntu/dists/xenial-updates/main/binary-amd64/by-hash/SHA256/64de74595313814f778183f24f18a8a416d31004444fed5b515fbf5681e38f01 HTTP/1.1\n\nHost: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* \nUser-Agent: Debian APT-HTTP/1.3 (1.2.24),Benign,Benign,None
8253,ascii,GET /ubuntu/dists/xenial-updates/main/i18n/by-hash/SHA256/6f25a9972e5d30d85ca1504f64590b330b451b28c6694ff7599781a389afb7c2 HTTP/1.1\n\nHost: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* \nUser-Agent: Debian APT-HTTP/1.3 (1.2.24),Benign,Benign,None
8271,ascii,GET /ubuntu/dists/xenial-updates/universe/binary-amd64/by-hash/SHA256/b353975a5d4f1a7272a5c785b9132f7b89f89d7d52c54df4d41ab8558d950319 HTTP/1.1\n\nHost: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* \nUser-Agent: Debian APT-HTTP/1.3 (1.2.24),Benign,Benign,None
8296,ascii,GET /ubuntu/dists/xenial-updates/universe/i18n/by-hash/SHA256/f401f39ea2728a4033d2de5f6b60b4953cc76dc51a6190ea3eca77993c08e934 HTTP/1.1\n\nHost: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* \nUser-Agent: Debian APT-HTTP/1.3 (1.2.24),Benign,Benign,None
14924,ascii,"GET / HTTP/1.1\n\nHost: 18.217.21.148 \nUser-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36 Connection: close",Benign,Benign,None
15037,ascii,GET /ccvv HTTP/1.1\n\nHost: 18.217.21.148 \nUser-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64) Accept-Encoding: gzip,Benign,Benign,None
15499,ascii,"GET /?yeFaFPSPb=C7QyhPv&UgNKvIPsv=7vDJjMKyc&Q5KQiWMnne=4TT6pw03jcLuu8W HTTP/1.1\nAccept-Encoding: '', gzip \nHost: 18.217.21.148 Keep-Alive: 517 Connection: keep-alive \nReferer: http://18.217.21.148/YIR0C8x Cache-Control: max-age=0 \nCookie: jJnyonYef=voS7nKir268erKjAu&KBTnQFuQWA=ETAvm&mj3f1pt=l8Aq8Gh7vIjmu \nUser-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) Gecko/20092106 Firefox/12.0",DoS-GoldenEye,Malicious,None
15504,ascii,GET /?cMgN=Iwh0UIGqayR&1t7gnC1=v2T1nWYAOWpd0ECMTS1r HTTP/1.1\nAccept-Encoding: identity Keep-Alive: 934 \nHost: 18.217.21.148 \nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0) Gecko/20082209 Firefox/10.0 Connection: keep-alive Cache-Control: no-cache \nContent-Type: multipart/form-data,DoS-GoldenEye,Malicious,None
15514,ascii,GET /?5r2ffD1=pnaBtx3GjwMBFjNoePh&xgBDaYC2=Mw5ybqlnExlb7u0CasuK&xlfGGvhJu=2nvBaDW7tWt&aopieOt=WSjHgE5fUNM&ULccVX=KkBpebM1 HTTP/1.1\n\nHost: 18.217.21.148 Accept-Encoding: deflate Keep-Alive: 937 \nUser-Agent: Mozilla/5.0 (Windows; U; MSIE 10.0; Windows NT 6.1; Trident/4.0; Win64; x64) Connection: keep-alive Cache-Control: no-cache \nContent-Type: application/x-url-encoded,DoS-GoldenEye,Malicious,None
15516,ascii,"GET /?dsytCyvo=BprUMPc66D70xCs HTTP/1.1\nAccept-Encoding: gzip, '' Connection: keep-alive Keep-Alive: 690 \nUser-Agent: Mozilla/5.0 (Linux i386; X11) Gecko/20101803 Firefox/11.0 \nHost: 18.217.21.148 \nCookie: dRL=iaGPkCLo6KKNUMCbgrf Cache-Control: max-age=0 \nReferer: http://18.217.21.148/7tWmmR7YnX?yJuTyG=LiMNIp68m1D",DoS-GoldenEye,Malicious,None
15526,ascii,"GET /?HlbobF=O2lTi7iqK HTTP/1.1\nAccept-Encoding: '', identity Connection: keep-alive Keep-Alive: 723 \nUser-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.1; .NET CLR 2.5.4620; Win64; x64) \nHost: 18.217.21.148 \nReferer: http://www.baidu.com/XHOtd Cache-Control: max-age=0 \nCookie: 1bvxyP=MfGkMyi8X0gC&T14KAsos=KNLYiXms3hdr6ODMTX&1kCf=JGA4XrluHYlE4TsmK \nContent-Type: multipart/form-data",DoS-GoldenEye,Malicious,None
15531,ascii,"GET /?Ymi5PsAn=yEtDvx56je0cx HTTP/1.1\nAccept-Encoding: '' Keep-Alive: 5 \nHost: 18.217.21.148 \nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_1) AppleWebKit/537.8 (KHTML, like Gecko) Chrome/18.0.847.90 Safari/537.10 Accept-Charset: utf-8,ISO-8859-2;q=0.9,*;q=0.6 Connection: keep-alive \nCookie: UojYX0=FTtQ&wlobX=7GuEcwq&QpwT5l=pcjk Cache-Control: no-cache \nContent-Type: application/x-url-encoded",DoS-GoldenEye,Malicious,None
15544,ascii,"GET /?634m=AN8I5twujO8Aw1TYAiv&FF0=CljAq6CMSYx6cUajNDY&IRHNfeMU=g2KmJKWbrTikFJs5 HTTP/1.1\nAccept-Encoding: gzip, '' Keep-Alive: 908 \nHost: 18.217.21.148 \nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_9_4) Gecko/20020806 Firefox/19.0 Accept-Charset: utf-8,Windows-1251;q=0.9,*;q=0.0 Connection: keep-alive Cache-Control: max-age=0",DoS-GoldenEye,Malicious,None
15549,ascii,"GET /?qq1hqOmm=GUntnLX&HB5=4hdF5Yf2Dx&I8NO=5CanyhF HTTP/1.1\nAccept-Encoding: identity, deflate Connection: keep-alive Keep-Alive: 781 \nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_8_3) Gecko/20102409 Firefox/17.0 Accept-Charset: ISO-8859-2,Windows-1251;q=1.0,*;q=1.0 \nHost: 18.217.21.148 \nCookie: R6t=VPRyUTW&igOHQ=klb5nfnIl3vLs8DeeUOE&akTr=tcWsR0NdxF Cache-Control: max-age=0",DoS-GoldenEye,Malicious,None

In [ ]:
import re, json
from urllib.parse import urlparse, parse_qs

def extract_from_payload_string(payload):
    try:
        if not isinstance(payload, str):
            return None

        lines = [l.strip() for l in payload.split("\n") if l.strip()]
        if not lines or len(lines[0].split()) < 2:  # More general, just method and path
            return None

        #Safe extraction of request line
        parts = lines[0].split()
        method = parts[0]
        full_path = parts[1] if len(parts) > 1 else "/"
        parsed = urlparse(full_path)
        path = parsed.path
        query = parsed.query
        query_dict = parse_qs(query)

        # extract headers and body
        headers = {}
        body = ""
        is_body = False

        for line in lines[1:]:
            if ":" in line and not is_body:
                k, v = line.split(":", 1)
                headers[k.strip().lower()] = v.strip()
            else:
                is_body = True
                body += line + " "

        #combine all attack surfaces
        combined = " ".join([
            body, query,
            headers.get("cookie", ""),
            headers.get("user-agent", ""),
            headers.get("referer", "")
        ]).lower()

        #matched keywords
        sql_patterns = [
            r"\bselect\b", r"\binsert\b", r"\bupdate\b", r"\bdelete\b", r"\bdrop\b", r"\bunion\b",
            r"\b(and|or)\b\s+[^\s]+\s*=\s*[^\s]+",
            r"['\"]\s*or\s*['\"]?\d+=\d+",
            r"\b\d+\s*=\s*\d+\b"
        ]
        sql_keywords = []
        for pattern in sql_patterns:
            sql_keywords += re.findall(pattern, combined)

        xss_patterns = [
            r"<script.*?>.*?</script>", r"(on\w+\s*=)", r"(document\.cookie)", r"(alert\s*\()",
            r"(eval\s*\()", r"(<img\s+[^>]*onerror\s*=)", r"(<svg\s+[^>]*onload\s*=)"
        ]
        xss_keywords = []
        for pattern in xss_patterns:
            xss_keywords += re.findall(pattern, combined)

        shell_patterns = [
            r"(curl|wget|bash|sh|nc|netcat|python|perl|powershell|cmd|scp|ftp)",
            r"(cmd(\.exe)?|powershell(\.exe)?)",
            r"/bin/(sh|bash|nc|cat)",
            r"(bash|sh)\s+-i",
            r"nc\s+-e\s+/bin/sh",
            r"exec\s+/bin/sh",
            r"(bash|sh)\s+-c\s+['\"].+?['\"]",
            r"powershell\s+-[eE]ncode[d]?",
            r"(?:wget|curl)\s+http[s]?://",
            r"rm\s+-rf\s+/",
            r"scp\s+\S+\s+\S+",
            r"\$\((.*?)\)",
            r"`.*?`",
            r"base64\s+-d",
            r"(?:(?:curl|wget|bash|sh|nc|netcat|python|perl|powershell|cmd|scp|ftp)[^;|&]{0,40})(\||;|&&)"
        ]
        shell_keywords = []
        for pattern in shell_patterns:
            shell_keywords += re.findall(pattern, combined)

        return {
            "method": method,
            "url_path": path,
            "query_parameters": json.dumps(query_dict),
            "user_agent": headers.get("user-agent", ""),
            "referer": headers.get("referer", ""),
            "cookies": headers.get("cookie", ""),
            "body": body.strip(),
            "sql_keywords": sql_keywords,
            "xss_keywords": xss_keywords,
            "shell_keywords": shell_keywords,
            "is_malicious": bool(sql_keywords or xss_keywords or shell_keywords)
        }

    except Exception as e:
        return None

In [172]:
sample = df["PayloadStrings"].iloc[1]
extract_from_payload_string(sample)

{'method': 'GET',
 'url_path': '/ubuntu/dists/xenial-updates/InRelease',
 'query_parameters': '{}',
 'user_agent': 'Debian APT-HTTP/1.3 (1.2.24)',
 'referer': '',
 'cookies': '',
 'body': '',
 'sql_keywords': [],
 'xss_keywords': [],
 'shell_keywords': [],
 'is_malicious': False}

In [ ]:
df["Parsed"] = df["PayloadStrings"].apply(extract_from_payload_string)
df_parsed = pd.DataFrame(df["Parsed"].dropna().tolist())

#Merge labels with extracted fields
df_final = pd.concat([df[["Label", "Attack"]].reset_index(drop=True), df_parsed], axis=1)


print(df_final.columns)
df_final.head()

Index(['Label', 'Attack', 'method', 'url_path', 'query_parameters',
       'user_agent', 'referer', 'cookies', 'body', 'sql_keywords',
       'xss_keywords', 'shell_keywords', 'is_malicious'],
      dtype='object')

,Label,Attack,method,url_path,query_parameters,user_agent,referer,cookies,body,sql_keywords,xss_keywords,shell_keywords,is_malicious
0,Benign,Benign,GET,/ubuntu/dists/xenial/InRelease,{},Debian APT-HTTP/1.3 (1.2.24),,,,[],[],[],False
1,Benign,Benign,GET,/ubuntu/dists/xenial-updates/InRelease,{},Debian APT-HTTP/1.3 (1.2.24),,,,[],[],[],False
2,Benign,Benign,GET,/ubuntu/dists/xenial-backports/InRelease,{},Debian APT-HTTP/1.3 (1.2.24),,,,[],[],[],False
3,Benign,Benign,GET,/ubuntu/dists/xenial-security/InRelease,{},Debian APT-HTTP/1.3 (1.2.24),,,,[],[],[],False
4,Benign,Benign,GET,/ubuntu/dists/xenial-updates/main/source/by-hash/SHA256/2dda3f2b8de307516800ca2121ee87893c84e2ea2e942df8ee261749130c2292,{},Debian APT-HTTP/1.3 (1.2.24),,,,[],[],[],False

In [173]:
print(df["PayloadStrings"].iloc[0])

GET /ubuntu/dists/xenial/InRelease HTTP/1.1

Host: us-east-2.ec2.archive.ubuntu.com Cache-Control: max-age=0 Accept: text/* If-Modified-Since: Thu, 21 Apr 2016 23:24:48 GMT
User-Agent: Debian APT-HTTP/1.3 (1.2.24)

In [175]:
df_final["clean_path"] = df_final["url_path"].apply(clean_text)
df_final["clean_query"] = df_final["query_parameters"].apply(clean_text)
df_final["clean_body"] = df_final["body"].apply(clean_text)
df_final["clean_user_agent"] = df_final["user_agent"].apply(clean_text)
df_final["clean_referer"] = df_final["referer"].apply(clean_text)
df_final["clean_cookies"] = df_final["cookies"].apply(clean_text)

In [176]:
df_final["nlp_text"] = (
    df_final["clean_path"] + " " +
    df_final["clean_query"] + " " +
    df_final["clean_body"] + " " +
    df_final["clean_user_agent"] + " " +
    df_final["clean_referer"] + " " +
    df_final["clean_cookies"]
).str.strip()

df_final["token_count"] = df_final["nlp_text"].apply(lambda x: len(x.split()))

In [178]:
columns_to_drop = [
     "url_path", "query_parameters", "user_agent", "referer", "cookies", "is_malicious", "Attack","body"
]

df_final.drop(columns=columns_to_drop, inplace=True, errors="ignore")

In [179]:
df_final.columns

Index(['Label', 'method', 'sql_keywords', 'xss_keywords', 'shell_keywords',
       'clean_path', 'clean_query', 'clean_body', 'clean_user_agent',
       'clean_referer', 'clean_cookies', 'nlp_text', 'token_count'],
      dtype='object')

In [ ]:
#config:
output_dir = "outpout_data"
os.makedirs(output_dir, exist_ok=True)

output_csv_path = os.path.join(output_dir, "final_structured_cleaned_payloads.csv")

#save: 
df_final.to_csv(output_csv_path, index=False)
print(f"Final dataset saved: '{output_csv_path}'")

print(df_final.sample(3))

final dataset saved: 'final_structured_cleaned_payloads.csv'
           Label method sql_keywords xss_keywords    shell_keywords  \
21504  Malicious    GET           []           []  [cmd, (cmd, , )]
52154  Malicious    GET           []           []                []
52190  Malicious    GET           []           []                []

      clean_path                            clean_query clean_body  \
21504             xgl2pln6 pwg0geqnipo hvq yg5eypwljoll
52154
52190

                                                                                                                                                                   clean_user_agent  \
21504  mozilla 5 0 windows nt 5 1 win64 x64 applewebkit 535 27 khtml like gecko chrome 15 0 1317 36 safari 536 16 accept charset iso 8859 1 utf 8 q 0 1 q 0 3 connection keep alive
52154           mozilla 4 0 compatible msie 7 0 windows nt 5 1 trident 4 0 net clr 1 1 4322 net clr 2 0 503l3 net clr 3 0 4506 2152 net clr 3 5 30729 msoffice 12 content length 42
52190           mozilla 4 0 compatible msie 7 0 windows nt 5 1 trident 4 0 net clr 1 1 4322 net clr 2 0 503l3 net clr 3 0 4506 2152 net clr 3 5 30729 msoffice 12 content length 42

      clean_referer  \
21504
52154
52190

                                                                                                                                   clean_cookies  \
21504  tcjcg1o8p fiaret1wnho6yt7t cegfpd ejaimyoigtgaq2 icjh whlp6civxe6nln0p esf1krm0ac 0u1o8omwfmt uw38ibcpio nmicmwof cache control max age 0
52154
52190

                                                                                                                                                                                                                                                                                                                                                             nlp_text  \
21504  xgl2pln6 pwg0geqnipo hvq yg5eypwljoll  mozilla 5 0 windows nt 5 1 win64 x64 applewebkit 535 27 khtml like gecko chrome 15 0 1317 36 safari 536 16 accept charset iso 8859 1 utf 8 q 0 1 q 0 3 connection keep alive  tcjcg1o8p fiaret1wnho6yt7t cegfpd ejaimyoigtgaq2 icjh whlp6civxe6nln0p esf1krm0ac 0u1o8omwfmt uw38ibcpio nmicmwof cache control max age 0
52154                                                                                                                                                                                             mozilla 4 0 compatible msie 7 0 windows nt 5 1 trident 4 0 net clr 1 1 4322 net clr 2 0 503l3 net clr 3 0 4506 2152 net clr 3 5 30729 msoffice 12 content length 42
52190                                                                                                                                                                                             mozilla 4 0 compatible msie 7 0 windows nt 5 1 trident 4 0 net clr 1 1 4322 net clr 2 0 503l3 net clr 3 0 4506 2152 net clr 3 5 30729 msoffice 12 content length 42

       token_count
21504           58
52154           40
52190           40

: